// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: api/sms.proto

package grpcIFace

import (
	reflect "reflect"
	sync "sync"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SmsState_State int32

const (
	SmsState_delivered     SmsState_State = 0
	SmsState_expired       SmsState_State = 1
	SmsState_undeliverable SmsState_State = 2
	SmsState_rejected      SmsState_State = 3
	SmsState_unknown       SmsState_State = 4
	SmsState_deleted       SmsState_State = 5
)

// Enum value maps for SmsState_State.
var (
	SmsState_State_name = map[int32]string{
		0: "delivered",
		1: "expired",
		2: "undeliverable",
		3: "rejected",
		4: "unknown",
		5: "deleted",
	}
	SmsState_State_value = map[string]int32{
		"delivered":     0,
		"expired":       1,
		"undeliverable": 2,
		"rejected":      3,
		"unknown":       4,
		"deleted":       5,
	}
)

func (x SmsState_State) Enum() *SmsState_State {
	p := new(SmsState_State)
	*p = x
	return p
}

func (x SmsState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SmsState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_api_sms_proto_enumTypes[0].Descriptor()
}

func (SmsState_State) Type() protoreflect.EnumType {
	return &file_api_sms_proto_enumTypes[0]
}

func (x SmsState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SmsState_State.Descriptor instead.
func (SmsState_State) EnumDescriptor() ([]byte, []int) {
	return file_api_sms_proto_rawDescGZIP(), []int{7, 0}
}

type SendMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items   []*SendMsgRequest_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Sender  string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Content string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *SendMsgRequest) Reset() {
	*x = SendMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgRequest) ProtoMessage() {}

func (x *SendMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgRequest.ProtoReflect.Descriptor instead.
func (*SendMsgRequest) Descriptor() ([]byte, []int) {
	return file_api_sms_proto_rawDescGZIP(), []int{0}
}

func (x *SendMsgRequest) GetItems() []*SendMsgRequest_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SendMsgRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SendMsgRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendMsgError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendMsgError) Reset() {
	*x = SendMsgError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMsgError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgError) ProtoMessage() {}

func (x *SendMsgError) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgError.ProtoReflect.Descriptor instead.
func (*SendMsgError) Descriptor() ([]byte, []int) {
	return file_api_sms_proto_rawDescGZIP(), []int{1}
}

func (x *SendMsgError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SendMsgError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BatchID string `protobuf:"bytes,1,opt,name=batchID,proto3" json:"batchID,omitempty"`
}

func (x *SendMsgResponse) Reset() {
	*x = SendMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgResponse) ProtoMessage() {}

func (x *SendMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgResponse.ProtoReflect.Descriptor instead.
func (*SendMsgResponse) Descriptor() ([]byte, []int) {
	return file_api_sms_proto_rawDescGZIP(), []int{2}
}

func (x *SendMsgResponse) GetBatchID() string {
	if x != nil {
		return x.BatchID
	}
	return ""
}

type ListByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ListByIDRequest) Reset() {
	*x = ListByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByIDRequest) ProtoMessage() {}

func (x *ListByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByIDRequest.ProtoReflect.Descriptor instead.
func (*ListByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_sms_proto_rawDescGZIP(), []int{3}
}

func (x *ListByIDRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type ListByTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//均为timestamp
	TimeBegin int64 `protobuf:"varint,1,opt,name=timeBegin,proto3" json:"timeBegin,omitempty"` //若未设置则默认为结束时间前2小时
	TimeEnd   int64 `protobuf:"varint,2,opt,name=timeEnd,proto3" json:"timeEnd,omitempty"`     //若为设置默认为当前时间
}

func (x *ListByTimeRequest) Reset() {
	*x = ListByTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListByTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByTimeRequest) ProtoMessage() {}

func (x *ListByTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByTimeRequest.ProtoReflect.Descriptor instead.
func (*ListByTimeRequest) Descriptor() ([]byte, []int) {
	return file_api_sms_proto_rawDescGZIP(), []int{4}
}

func (x *ListByTimeRequest) GetTimeBegin() int64 {
	if x != nil {
		return x.TimeBegin
	}
	return 0
}

func (x *ListByTimeRequest) GetTimeEnd() int64 {
	if x != nil {
		return x.TimeEnd
	}
	return 0
}

type SmsContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender        string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	To            string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	BatchID       string `protobuf:"bytes,3,opt,name=batchID,proto3" json:"batchID,omitempty"`
	SendMessageID string `protobuf:"bytes,4,opt,name=sendMessageID,proto3" json:"sendMessageID,omitempty"`
	Content       string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Time          int64  `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *SmsContent) Reset() {
	*x = SmsContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsContent) ProtoMessage() {}

func (x *SmsContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsContent.ProtoReflect.Descriptor instead.
func (*SmsContent) Descriptor() ([]byte, []int) {
	return file_api_sms_proto_rawDescGZIP(), []int{5}
}

func (x *SmsContent) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SmsContent) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SmsContent) GetBatchID() string {
	if x != nil {
		return x.BatchID
	}
	return ""
}

func (x *SmsContent) GetSendMessageID() string {
	if x != nil {
		return x.SendMessageID
	}
	return ""
}

func (x *SmsContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SmsContent) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type ListContentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32         `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Mails []*SmsContent `protobuf:"bytes,2,rep,name=mails,proto3" json:"mails,omitempty"`
}

func (x *ListContentsResponse) Reset() {
	*x = ListContentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentsResponse) ProtoMessage() {}

func (x *ListContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentsResponse.ProtoReflect.Descriptor instead.
func (*ListContentsResponse) Descriptor() ([]byte, []int) {
	return file_api_sms_proto_rawDescGZIP(), []int{6}
}

func (x *ListContentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListContentsResponse) GetMails() []*SmsContent {
	if x != nil {
		return x.Mails
	}
	return nil
}

type SmsState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To            string         `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	BatchID       string         `protobuf:"bytes,2,opt,name=batchID,proto3" json:"batchID,omitempty"`
	SendMessageID string         `protobuf:"bytes,3,opt,name=sendMessageID,proto3" json:"sendMessageID,omitempty"`
	RecvMessageID string         `protobuf:"bytes,4,opt,name=RecvMessageID,proto3" json:"RecvMessageID,omitempty"`
	State         SmsState_State `protobuf:"varint,5,opt,name=state,proto3,enum=SmsState_State" json:"state,omitempty"`
	SubmitTime    int64          `protobuf:"varint,6,opt,name=submitTime,proto3" json:"submitTime,omitempty"`
	DownTime      int64          `protobuf:"varint,7,opt,name=downTime,proto3" json:"downTime,omitempty"`
	OriginResult  string         `protobuf:"bytes,8,opt,name=originResult,proto3" json:"originResult,omitempty"`
}

func (x *SmsState) Reset() {
	*x = SmsState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsState) ProtoMessage() {}

func (x *SmsState) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsState.ProtoReflect.Descriptor instead.
func (*SmsState) Descriptor() ([]byte, []int) {
	return file_api_sms_proto_rawDescGZIP(), []int{7}
}

func (x *SmsState) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SmsState) GetBatchID() string {
	if x != nil {
		return x.BatchID
	}
	return ""
}

func (x *SmsState) GetSendMessageID() string {
	if x != nil {
		return x.SendMessageID
	}
	return ""
}

func (x *SmsState) GetRecvMessageID() string {
	if x != nil {
		return x.RecvMessageID
	}
	return ""
}

func (x *SmsState) GetState() SmsState_State {
	if x != nil {
		return x.State
	}
	return SmsState_delivered
}

func (x *SmsState) GetSubmitTime() int64 {
	if x != nil {
		return x.SubmitTime
	}
	return 0
}

func (x *SmsState) GetDownTime() int64 {
	if x != nil {
		return x.DownTime
	}
	return 0
}

func (x *SmsState) GetOriginResult() string {
	if x != nil {
		return x.OriginResult
	}
	return ""
}

type ListStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	State []*SmsState `protobuf:"bytes,2,rep,name=state,proto3" json:"state,omitempty"`
}

func (x *ListStateResponse) Reset() {
	*x = ListStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStateResponse) ProtoMessage() {}

func (x *ListStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStateResponse.ProtoReflect.Descriptor instead.
func (*ListStateResponse) Descriptor() ([]byte, []int) {
	return file_api_sms_proto_rawDescGZIP(), []int{8}
}

func (x *ListStateResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListStateResponse) GetState() []*SmsState {
	if x != nil {
		return x.State
	}
	return nil
}

type CallbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total    int32                       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Type     string                      `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DataList []*CallbackRequest_DataList `protobuf:"bytes,3,rep,name=dataList,proto3" json:"dataList,omitempty"`
}

func (x *CallbackRequest) Reset() {
	*x = CallbackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackRequest) ProtoMessage() {}

func (x *CallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackRequest.ProtoReflect.Descriptor instead.
func (*CallbackRequest) Descriptor() ([]byte, []int) {
	return file_api_sms_proto_rawDescGZIP(), []int{9}
}

func (x *CallbackRequest) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CallbackRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CallbackRequest) GetDataList() []*CallbackRequest_DataList {
	if x != nil {
		return x.DataList
	}
	return nil
}

type CallbackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CallbackResponse) Reset() {
	*x = CallbackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackResponse) ProtoMessage() {}

func (x *CallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackResponse.ProtoReflect.Descriptor instead.
func (*CallbackResponse) Descriptor() ([]byte, []int) {
	return file_api_sms_proto_rawDescGZIP(), []int{10}
}

type SendMsgRequest_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To        string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	MessageID string `protobuf:"bytes,2,opt,name=messageID,proto3" json:"messageID,omitempty"`
}

func (x *SendMsgRequest_Item) Reset() {
	*x = SendMsgRequest_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMsgRequest_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgRequest_Item) ProtoMessage() {}

func (x *SendMsgRequest_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgRequest_Item.ProtoReflect.Descriptor instead.
func (*SendMsgRequest_Item) Descriptor() ([]byte, []int) {
	return file_api_sms_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SendMsgRequest_Item) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendMsgRequest_Item) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

type CallbackRequest_DataList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone        string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Reserve      string `protobuf:"bytes,2,opt,name=reserve,proto3" json:"reserve,omitempty"`
	Uuid         string `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	MsgID        string `protobuf:"bytes,4,opt,name=msgID,proto3" json:"msgID,omitempty"`
	CustomMsgID  string `protobuf:"bytes,5,opt,name=customMsgID,proto3" json:"customMsgID,omitempty"`
	State        int32  `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	SubmitTime   string `protobuf:"bytes,7,opt,name=submitTime,proto3" json:"submitTime,omitempty"`
	OriginResult string `protobuf:"bytes,8,opt,name=originResult,proto3" json:"originResult,omitempty"`
	DoneTime     string `protobuf:"bytes,9,opt,name=doneTime,proto3" json:"doneTime,omitempty"`
}

func (x *CallbackRequest_DataList) Reset() {
	*x = CallbackRequest_DataList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sms_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallbackRequest_DataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackRequest_DataList) ProtoMessage() {}

func (x *CallbackRequest_DataList) ProtoReflect() protoreflect.Message {
	mi := &file_api_sms_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackRequest_DataList.ProtoReflect.Descriptor instead.
func (*CallbackRequest_DataList) Descriptor() ([]byte, []int) {
	return file_api_sms_proto_rawDescGZIP(), []int{9, 0}
}

func (x *CallbackRequest_DataList) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CallbackRequest_DataList) GetReserve() string {
	if x != nil {
		return x.Reserve
	}
	return ""
}

func (x *CallbackRequest_DataList) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CallbackRequest_DataList) GetMsgID() string {
	if x != nil {
		return x.MsgID
	}
	return ""
}

func (x *CallbackRequest_DataList) GetCustomMsgID() string {
	if x != nil {
		return x.CustomMsgID
	}
	return ""
}

func (x *CallbackRequest_DataList) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *CallbackRequest_DataList) GetSubmitTime() string {
	if x != nil {
		return x.SubmitTime
	}
	return ""
}

func (x *CallbackRequest_DataList) GetOriginResult() string {
	if x != nil {
		return x.OriginResult
	}
	return ""
}

func (x *CallbackRequest_DataList) GetDoneTime() string {
	if x != nil {
		return x.DoneTime
	}
	return ""
}

var File_api_sms_proto protoreflect.FileDescriptor

var file_api_sms_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x01,
	0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x34,
	0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x44, 0x22, 0x3c, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49, 0x44, 0x22,
	0x21, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x44, 0x22, 0x4b, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x42,
	0x65, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x22,
	0xa2, 0x01, 0x0a, 0x0a, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49, 0x44,
	0x12, 0x24, 0x0a, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x22, 0x4f, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x21, 0x0a, 0x05, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x05,
	0x6d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0xe7, 0x02, 0x0a, 0x08, 0x53, 0x6d, 0x73, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d,
	0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x76, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x52, 0x65, 0x63, 0x76, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x12, 0x25, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x53, 0x6d, 0x73, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x5e, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x64, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x75, 0x6e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x72, 0x65, 0x6a, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x05, 0x22,
	0x4a, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1f, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x53, 0x6d, 0x73, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0xf1, 0x02, 0x0a, 0x0f,
	0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x64, 0x61, 0x74,
	0x61, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x43, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74,
	0x1a, 0xfc, 0x01, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x12, 0x0a, 0x10, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x3c, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x32, 0x0a,
	0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0f, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x32, 0x7f, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x39, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74,
	0x4c, 0x6f, 0x67, 0x73, 0x42, 0x79, 0x49, 0x44, 0x12, 0x10, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42,
	0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x73, 0x42,
	0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x54, 0x69,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x32, 0x7d, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x0d, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x79, 0x49, 0x44, 0x12, 0x10, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x42, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79,
	0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x32, 0x55, 0x0a, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x49, 0x0a,
	0x0c, 0x52, 0x65, 0x63, 0x76, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x10, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x22, 0x09, 0x2f, 0x63, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x3a, 0x01, 0x2a, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x6b, 0x67, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x49, 0x46, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_sms_proto_rawDescOnce sync.Once
	file_api_sms_proto_rawDescData = file_api_sms_proto_rawDesc
)

func file_api_sms_proto_rawDescGZIP() []byte {
	file_api_sms_proto_rawDescOnce.Do(func() {
		file_api_sms_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_sms_proto_rawDescData)
	})
	return file_api_sms_proto_rawDescData
}

var file_api_sms_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_sms_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_sms_proto_goTypes = []interface{}{
	(SmsState_State)(0),              // 0: SmsState.State
	(*SendMsgRequest)(nil),           // 1: SendMsgRequest
	(*SendMsgError)(nil),             // 2: SendMsgError
	(*SendMsgResponse)(nil),          // 3: SendMsgResponse
	(*ListByIDRequest)(nil),          // 4: ListByIDRequest
	(*ListByTimeRequest)(nil),        // 5: ListByTimeRequest
	(*SmsContent)(nil),               // 6: SmsContent
	(*ListContentsResponse)(nil),     // 7: ListContentsResponse
	(*SmsState)(nil),                 // 8: SmsState
	(*ListStateResponse)(nil),        // 9: ListStateResponse
	(*CallbackRequest)(nil),          // 10: CallbackRequest
	(*CallbackResponse)(nil),         // 11: CallbackResponse
	(*SendMsgRequest_Item)(nil),      // 12: SendMsgRequest.Item
	(*CallbackRequest_DataList)(nil), // 13: CallbackRequest.DataList
}
var file_api_sms_proto_depIdxs = []int32{
	12, // 0: SendMsgRequest.items:type_name -> SendMsgRequest.Item
	6,  // 1: ListContentsResponse.mails:type_name -> SmsContent
	0,  // 2: SmsState.state:type_name -> SmsState.State
	8,  // 3: ListStateResponse.state:type_name -> SmsState
	13, // 4: CallbackRequest.dataList:type_name -> CallbackRequest.DataList
	1,  // 5: Sender.SendMessage:input_type -> SendMsgRequest
	4,  // 6: Log.ListLogsByID:input_type -> ListByIDRequest
	5,  // 7: Log.ListLogsByTime:input_type -> ListByTimeRequest
	4,  // 8: State.ListStateByID:input_type -> ListByIDRequest
	5,  // 9: State.ListStateByTime:input_type -> ListByTimeRequest
	10, // 10: Callback.RecvCallback:input_type -> CallbackRequest
	3,  // 11: Sender.SendMessage:output_type -> SendMsgResponse
	7,  // 12: Log.ListLogsByID:output_type -> ListContentsResponse
	7,  // 13: Log.ListLogsByTime:output_type -> ListContentsResponse
	9,  // 14: State.ListStateByID:output_type -> ListStateResponse
	9,  // 15: State.ListStateByTime:output_type -> ListStateResponse
	11, // 16: Callback.RecvCallback:output_type -> CallbackResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_sms_proto_init() }
func file_api_sms_proto_init() {
	if File_api_sms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_sms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMsgError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sms_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListByTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sms_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sms_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListContentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sms_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sms_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sms_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallbackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sms_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallbackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sms_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMsgRequest_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sms_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallbackRequest_DataList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_sms_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_api_sms_proto_goTypes,
		DependencyIndexes: file_api_sms_proto_depIdxs,
		EnumInfos:         file_api_sms_proto_enumTypes,
		MessageInfos:      file_api_sms_proto_msgTypes,
	}.Build()
	File_api_sms_proto = out.File
	file_api_sms_proto_rawDesc = nil
	file_api_sms_proto_goTypes = nil
	file_api_sms_proto_depIdxs = nil
}
